{
  "window": { "opacity": 0.8 },
  "key_bindings":
    [
      { "key": "F", "mods": "Command|Control", "action": "ToggleFullscreen" },
      { "key": "W", "mods": "Command", "action": "CreateNewWindow" },
    ],
}
